- core-bank/src/main/java/com/example/core_bank/core_bank/exception/GlobalExceptionHandler.java
- core-bank/src/main/java/com/example/core_bank/core_bank/model/Account.java
- core-bank/src/main/java/com/example/core_bank/core_bank/model/Authentication.java
- core-bank/src/main/java/com/example/core_bank/core_bank/model/Bank.java
- core-bank/src/main/java/com/example/core_bank/core_bank/model/BusinessNumber.java
- core-bank/src/main/java/com/example/core_bank/core_bank/model/Classfication.java
- core-bank/src/main/java/com/example/core_bank/core_bank/model/TransactionHistory.java
- core-bank/src/main/resources/application.yaml
> Zgsj 31/feature/core banking setup

- core-bank/src/main/java/com/example/core_bank/core_bank/model/Account.java
- core-bank/src/main/java/com/example/core_bank/core_bank/model/Authentication.java
- core-bank/src/main/java/com/example/core_bank/core_bank/model/Bank.java
- core-bank/src/main/java/com/example/core_bank/core_bank/model/BusinessNumber.java
- core-bank/src/main/java/com/example/core_bank/core_bank/model/Classfication.java
- core-bank/src/main/java/com/example/core_bank/core_bank/model/TransactionHistory.java
엔티티 타입 변경으로  , 테스트 없이 진행
엔티티 타입 변경으로  , 테스트 없이 진행했습니다.
> hotfix: 엔티티 타입 참조형으로 변경

- User/src/main/java/com/example/User/model/Employee.java
- User/src/main/java/com/example/User/model/President.java
User 프로젝트의
- President 엔티티 구현
- Employee 엔티티 구현
테스트는 따로 진행 안 했습니다
> feat: president, employee 엔티티 구현

- User/src/main/java/com/example/User/controller/ValidationController.java
- User/src/main/java/com/example/User/dto/businessnumber/BusinessNumberRequest.java
- User/src/main/java/com/example/User/dto/businessnumber/BusinessNumberResponse.java
- User/src/main/java/com/example/User/feign/CoreBankFeign.java
- User/src/main/java/com/example/User/service/ValidationService.java
- User/src/test/java/com/example/User/controller/ValidationControllerTest.java
- core-bank/src/main/java/com/example/core_bank/core_bank/controller/BusinessNumberController.java
- core-bank/src/main/java/com/example/core_bank/core_bank/dto/businessnumber/BusinessNumberResponse.java
- core-bank/src/main/java/com/example/core_bank/core_bank/exception/BusinessNumberException.java
- core-bank/src/main/java/com/example/core_bank/core_bank/exception/GlobalExceptionHandler.java
- core-bank/src/main/java/com/example/core_bank/core_bank/repository/BusinessNumberRepository.java
- core-bank/src/main/java/com/example/core_bank/core_bank/service/BusinessNumberService.java
사업자 번호 확인 로직 구현
POSTMAN 테스트, JUNIT 테스트 완료
- [V] 코드 컨벤션을 준수하였는가?
- [V] 모든 테스트가 통과하는가?
외부 통신 로직 토대이므로, 팀원들 확인 바랍니다.
> feat: 사업자 번호 확인 로직 구현

- User/src/main/java/com/example/User/model/Employee.java
- User/src/main/java/com/example/User/model/President.java
- User/src/main/java/com/example/User/model/Store.java
- User/src/main/java/com/example/User/model/StoreEmployee.java
> feat: user엔티티 수정

- User/src/main/java/com/example/User/controller/PresidentController.java
- User/src/main/java/com/example/User/dto/presidentupdate/PresidentUpdateRequest.java
- User/src/main/java/com/example/User/repository/PresidentRepository.java
- User/src/main/java/com/example/User/service/PresidentService.java
> feat:사장 정보 수정

- API-Gateway/src/main/java/com/example/API_Gateway/filter/TokenCheckFilter.java
- Attendance/build.gradle
- Attendance/src/main/java/com/example/Attendance/Repository/CommuteRepository.java
- Attendance/src/main/java/com/example/Attendance/Repository/StoreEmployeeRepository.java
- Attendance/src/main/java/com/example/Attendance/Repository/StoreRepository.java
- Attendance/src/main/java/com/example/Attendance/controller/StoreEmployeeController.java
- Attendance/src/main/java/com/example/Attendance/dto/EmployeeCommuteRequest.java
- Attendance/src/main/java/com/example/Attendance/error/ErrorCode.java
- Attendance/src/main/java/com/example/Attendance/model/Commute.java
- Attendance/src/main/java/com/example/Attendance/model/Store.java
- Attendance/src/main/java/com/example/Attendance/service/MapService.java
- Attendance/src/main/java/com/example/Attendance/service/StoreEmployeeService.java
- Attendance/src/main/java/com/example/Attendance/service/StoreService.java
> feat: qr 출퇴근 로직 작성

- core-bank/src/main/resources/application.yaml
> refactor: yml 중요 정보 환경변수로 변경

- User/src/main/java/com/example/User/dto/store/StoreRequest.java
> hotfix: user store엔티티 수정

- User/src/main/java/com/example/User/config/UserConfig.java
- User/src/main/java/com/example/User/controller/AuthController.java
- User/src/main/java/com/example/User/controller/PresidentController.java
- User/src/main/java/com/example/User/controller/StoreController.java
- User/src/main/java/com/example/User/error/ErrorCode.java
- User/src/main/java/com/example/User/resolver/MasterId.java
- User/src/main/java/com/example/User/resolver/MasterIdArgumentResolver.java
- User/src/main/java/com/example/User/service/StoreService.java
ID 필요 로직에 주입
네
- [V] 코드 컨벤션을 준수하였는가?
X
> feat: 사장님 id 필요 주입+ 주입 방식 ArgumentResolver 사용

- API-Gateway/src/main/java/com/example/API_Gateway/SecurityConfig.java
gateway - SecurityConfig - tokenCheckFilter에  url 추가했습니다.
> fix: 아이디 찾기 기능 gateway - SecurityConfig

- API-Gateway/src/main/java/com/example/API_Gateway/SecurityConfig.java
- User/src/main/java/com/example/User/controller/PresidentController.java
- User/src/main/java/com/example/User/dto/president/PresidentInfoResponse.java
- User/src/main/java/com/example/User/resolver/MasterIdArgumentResolver.java
- User/src/main/java/com/example/User/service/PresidentService.java
- User/src/test/java/com/example/User/service/PresidentServiceTest.java
> Feat/zgsj 129  api /사장님마이페이지구현

- API-Gateway/src/main/java/com/example/API_Gateway/SecurityConfig.java
- User/src/main/java/com/example/User/model/President.java
- User/src/main/java/com/example/User/model/Store.java
- User/src/main/java/com/example/User/repository/StoreEmployeeRepository.java
- User/src/main/java/com/example/User/service/StoreEmployeeService.java
- User/src/test/java/com/example/User/service/StoreEmployeeServiceTest.java
0. DDL CASCADE 추가
1. 사장 Table은 양방향이므로, casacade로 제거 추가 (model)
2. Attendance 부는 model 폴더에서 변경 x
3. soft delete+masking으로 변경
postman + testcode 작성 완료
- [V] 코드 컨벤션을 준수하였는가?
- [V] 모든 테스트가 통과하는가?
> feat: delete cascade 추가. 

- Attendance/src/main/java/com/example/Attendance/controller/StoreEmployeeController.java
- Attendance/src/main/java/com/example/Attendance/dto/EmployeeCommuteRequest.java
- Attendance/src/main/java/com/example/Attendance/error/ErrorCode.java
- Attendance/src/main/java/com/example/Attendance/model/StoreEmployee.java
- Attendance/src/main/java/com/example/Attendance/service/CommuteService.java
- Attendance/src/main/java/com/example/Attendance/service/StoreEmployeeService.java
- Attendance/src/main/java/com/example/Attendance/util/Cryptography.java
- Attendance/src/test/java/com/example/Attendance/service/CommuteServiceTest.java
- Attendance/src/test/java/com/example/Attendance/service/StoreEmployeeServiceTest.java
- User/src/main/java/com/example/User/controller/StoreController.java
- User/src/main/java/com/example/User/controller/StoreEmployeeController.java
- User/src/main/java/com/example/User/dto/storeemployee/StoreEmployeeRequest.java
- User/src/main/java/com/example/User/error/ErrorCode.java
- User/src/main/java/com/example/User/service/EmailService.java
- User/src/main/java/com/example/User/service/StoreEmployeeService.java
- User/src/main/java/com/example/User/service/StoreService.java
- User/src/main/java/com/example/User/util/JWTUtil.java
- User/src/main/java/com/example/User/util/QRCodeUtil.java
- User/src/test/java/com/example/User/service/EmailServiceTest.java
- User/src/test/java/com/example/User/service/StoreServiceTest.java
예 
서비스 로직 변경에 따른  테스트 수정 및 포스트맨 체크 완료
> feat: 출퇴근 로직 변경

- Attendance/src/main/java/com/example/Attendance/controller/PayStatementController.java
- Attendance/src/main/java/com/example/Attendance/dto/PayStatementResponse.java
- Attendance/src/main/java/com/example/Attendance/error/ErrorCode.java
- Attendance/src/main/java/com/example/Attendance/repository/PayStatementRepository.java
- Attendance/src/main/java/com/example/Attendance/service/PayStatementService.java
- Attendance/src/test/java/com/example/Attendance/repository/PayStatementRepositoryTest.java
- Attendance/src/test/java/com/example/Attendance/service/PayStatementServiceTest.java
급여 기록 조회 api 생성
쿼리 관련 질문있으면 알려주세요
> Feat/zgsj 61  /급여기록조회

- API-Gateway/src/main/java/com/example/API_Gateway/SecurityConfig.java
- API-Gateway/src/main/java/com/example/API_Gateway/util/CryptoUtil.java
- Attendance/src/main/java/com/example/Attendance/controller/StoreEmployeeController.java
- Attendance/src/main/java/com/example/Attendance/dto/EmployeeCommuteRequest.java
- User/src/main/java/com/example/User/service/EmailService.java
- User/src/main/java/com/example/User/util/CryptoUtil.java
> Refactor: commute 프론트 통신할때 변경점

- Attendance/src/main/java/com/example/Attendance/controller/CommuteController.java
- Attendance/src/main/java/com/example/Attendance/dto/CommuteDailyResponse.java
- Attendance/src/main/java/com/example/Attendance/repository/CommuteRepository.java
- Attendance/src/main/java/com/example/Attendance/service/CommuteService.java
- Attendance/src/test/java/com/example/Attendance/service/CommuteServiceTest.java
> Feat/zgsj 74/일별출근자조회

- Attendance/src/main/java/com/example/Attendance/dto/BatchInputData.java
- Attendance/src/main/java/com/example/Attendance/dto/CommuteDailyResponse.java
- Attendance/src/main/java/com/example/Attendance/model/StoreEmployee.java
- Attendance/src/main/java/com/example/Attendance/service/CommuteService.java
- Attendance/src/test/java/com/example/Attendance/service/CommuteServiceTest.java
- User/src/main/java/com/example/User/dto/storeemployee/EmployeeInfoResponse.java
- User/src/main/java/com/example/User/dto/storeemployee/StoreEmployeeRequest.java
- User/src/main/java/com/example/User/model/StoreEmployee.java
- core-bank/src/test/java/com/example/core_bank/core_bank/service/BankCoreServiceTest.java
직원 타입 -> byte, 출석에 생일, 전화번호 추가
포스트맨 몇개 돌려봤습니다
> hotfix: 유저 및 출석 엔티티 수정 및 그에 따른 연관 객체 수정

- Finance/src/main/java/com/example/Finance/error/GlobalExceptionHandler.java
- Finance/src/main/java/com/example/Finance/service/TransactionHistoryService.java
1.차트 계산 로직 수정
2.finance 부 feignexception 추가
네(postman)
> Fix/zgsj 174  2/차트수정

- Finance/src/main/java/com/example/Finance/controller/FinanceController.java
- Finance/src/main/java/com/example/Finance/dto/TransactionHistoryWithCounterPartyResponse.java
- Finance/src/main/java/com/example/Finance/feign/CoreBankFeign.java
- Finance/src/main/java/com/example/Finance/service/SimpleLedgerPdfService.java
- Finance/src/main/java/com/example/Finance/service/TransactionHistoryService.java
- core-bank/src/main/java/com/example/core_bank/core_bank/core/controller/TransactionHistoryController.java
- core-bank/src/main/java/com/example/core_bank/core_bank/core/dto/TransactionHistoryWithCounterPartyResponse.java
- core-bank/src/main/java/com/example/core_bank/core_bank/core/repository/TransactionHistoryRepository.java
- core-bank/src/main/java/com/example/core_bank/core_bank/core/service/TransactionHistoryService.java
- core-bank/src/test/java/com/example/core_bank/core_bank/core/repository/TransactionHistoryRepositoryTest.java
간편장부 생성 기능 추가
postman + 단위 테스트 진행했습니다.
> Feat/zgsj 168  /간편장부생성

- User/src/main/java/com/example/User/controller/CoreBankController.java
- User/src/main/java/com/example/User/feign/CoreBankFeign.java
- User/src/main/java/com/example/User/service/CoreBankService.java
- core-bank/src/main/java/com/example/core_bank/core_bank/core/controller/AccountVerifyController.java
postman으로 확인했을 때 사장계좌확인, 직원계좌 확인 기능 정상작동 합니다!
> Feat/zgsj 172  api 직원계좌인증api구현

- User/src/main/java/com/example/User/controller/PresidentAccountController.java
- User/src/main/java/com/example/User/repository/PresidentRepository.java
- User/src/main/java/com/example/User/service/PresidentService.java
이메일 중복 체크 로직 추가 했습니다. (repository, service, controller)
테스트 완료 매우 잘됩니다.
> feat: 이메일 중복 체크 로직 추가

- User/src/main/java/com/example/User/repository/StoreEmployeeRepository.java
fix : 직원 삭제 시 마스킹 제외, 직원 타입만 10으로 변경
> fix : 직원 삭제시 마스킹 제외, employementtype만 10으로 변경

- API-Gateway/src/main/java/com/example/API_Gateway/SecurityConfig.java
- User/src/main/java/com/example/User/controller/AuthController.java
- User/src/main/java/com/example/User/dto/passwordemail/PassWordValidate.java
- User/src/main/java/com/example/User/error/ErrorCode.java
- User/src/main/java/com/example/User/service/AuthService.java
- User/src/test/java/com/example/User/service/AuthServiceTest.java
- User/src/test/java/com/example/User/service/ValidateTest.java
가게 삭제 시 비밀번호 확인 로직 추가 
테스트 코드 작성 완료 
> Feat/zgsj 156  /가게삭제시비밀번호확인

- core-bank/src/main/java/com/example/core_bank/core_bank/core/controller/TestRemoveController.java
> feat: 코어뱅킹 ci/cd 테스트 용도

- User/src/main/java/com/example/User/controller/StoreController.java
- User/src/main/java/com/example/User/model/Store.java
- User/src/main/java/com/example/User/repository/StoreRepository.java
- User/src/main/java/com/example/User/service/StoreService.java
가게 수정시 이름 중복 체크, 가게 정보 수정 수정
포스트맨 확인 완
> feat: 가게이름 중복, 가게 정보 수정 수정

- .github/workflows/attendance-deploy.yml
- .github/workflows/core-bank-deploy.yml
- Attendance/Dockerfile
- Attendance/src/main/java/com/example/Attendance/controller/TestController.java
- Attendance/src/main/resources/application.yml
- core-bank/Dockerfile
> attendance 배포 완료

- core-bank/src/main/resources/application.yml
> feat: 코어 뱅킹 yml 추가

- .github/workflows/finance-deploy.yml
- Finance/Dockerfile
- Finance/src/main/resources/application.yml
> feat: finance ci/cd 생성

- .github/workflows/finance-deploy.yml
- Finance/src/main/java/com/example/Finance/controller/FinanceController.java
> feat: finance ci/cd 수정

- .github/workflows/api-gateway-deploy.yml
- API-Gateway/Dockerfile
- API-Gateway/src/main/resources/application.yml
- Finance/Dockerfile
> feat: api-gateway ci/cd 추가

- .github/workflows/user-deploy.yml
- User/Dockerfile
- User/src/main/java/com/example/User/dto/login/TokensResponse.java
- User/src/main/java/com/example/User/dto/store/StoreUpdateRequest.java
- User/src/main/resources/application.yml
> feat: user ci/cd 추가

- .github/workflows/user-deploy.yml
> feat: user ci/cd 수정

- Attendance/src/main/java/com/example/Attendance/FeignWithCoreBank.java
- Finance/src/main/java/com/example/Finance/feign/CoreBankFeign.java
- User/src/main/java/com/example/User/feign/CoreBankFeign.java
corebank 부 port 변경 
진행 후 테스트 예정 (배포 환경에서의 테스트 목표)
-
> fix : core bank feign port 변경

- User/src/main/java/com/example/User/error/ErrorCode.java
- User/src/main/java/com/example/User/service/EmailService.java
존재하지 않는 이메일에 대한 Exception 처리했습니다.
해당 문제 입니다.
Postman을 통해 Test 진행했습니다.
> refactor : 존재하지 않는 이메일에 대한 Exception 처리

- Attendance/src/main/java/com/example/Attendance/config/GCPConfig.java
> feat: json-> string 환견변수로 변경

- API-Gateway/src/main/java/com/example/API_Gateway/SecurityConfig.java
- Attendance/src/main/java/com/example/Attendance/model/President.java
- Attendance/src/main/java/com/example/Attendance/repository/StoreEmployeeRepository.java
- User/src/main/java/com/example/User/controller/PresidentInfoController.java
- User/src/main/java/com/example/User/dto/president/TermAcceptRequest.java
- User/src/main/java/com/example/User/error/ErrorCode.java
- User/src/main/java/com/example/User/model/President.java
- User/src/main/java/com/example/User/repository/PresidentRepository.java
- User/src/main/java/com/example/User/service/PresidentService.java
attendance 사장님 terms accept entity 추가,batch에 적용 및 termaccept 변경 api구현
> terms accept 관련 수정

- Attendance/src/main/java/com/example/Attendance/error/ErrorCode.java
- Attendance/src/main/java/com/example/Attendance/service/EmailService.java
- User/src/main/java/com/example/User/controller/AccountAuthController.java
- User/src/main/java/com/example/User/controller/AuthController.java
- User/src/main/java/com/example/User/controller/CoreBankController.java
- User/src/main/java/com/example/User/controller/ManagerController.java
- User/src/main/java/com/example/User/controller/PresidentAccountController.java
- User/src/main/java/com/example/User/controller/ValidationController.java
- User/src/main/java/com/example/User/dto/response/ResponseDto.java
- User/src/main/java/com/example/User/error/ErrorCode.java
- User/src/main/java/com/example/User/service/EmailService.java
- User/src/main/java/com/example/User/service/PresidentService.java
Front 작업 시 예외 처리를 위해 Backend부 응답을 통일했습니다
(기존 boolean ->ResponseDto)
Postman을 통한 확인 완료 
> Fix : response통일

- Attendance/src/main/java/com/example/Attendance/service/batch/PdfService.java
- Finance/src/main/java/com/example/Finance/service/PdfService.java
> fix: pdf 서비스 수정

- API-Gateway/src/main/java/com/example/API_Gateway/SecurityConfig.java
- Attendance/src/main/java/com/example/Attendance/error/ErrorCode.java
- Attendance/src/main/java/com/example/Attendance/service/EmailService.java
- Attendance/src/main/java/com/example/Attendance/service/batch/PdfService.java
- Finance/src/main/java/com/example/Finance/service/PdfService.java
- User/src/main/java/com/example/User/controller/AccountAuthController.java
- User/src/main/java/com/example/User/controller/AuthController.java
- User/src/main/java/com/example/User/controller/CoreBankController.java
- User/src/main/java/com/example/User/controller/ManagerController.java
- User/src/main/java/com/example/User/controller/PresidentAccountController.java
- User/src/main/java/com/example/User/controller/ValidationController.java
- User/src/main/java/com/example/User/dto/response/ResponseDto.java
- User/src/main/java/com/example/User/error/ErrorCode.java
- User/src/main/java/com/example/User/service/EmailService.java
- User/src/main/java/com/example/User/service/ManagerService.java
- User/src/main/java/com/example/User/service/PresidentService.java
> Zgsj 191  user api 관리자 사장님조회

- API-Gateway/src/main/java/com/example/API_Gateway/SecurityConfig.java
- User/src/main/java/com/example/User/controller/AccountAuthController.java
- User/src/main/java/com/example/User/dto/authserver/AuthServerOnlyPinNumberRequest.java
- User/src/main/java/com/example/User/dto/authserver/AuthServerPinNumberRequest.java
- User/src/main/java/com/example/User/error/ErrorCode.java
- User/src/main/java/com/example/User/service/PresidentService.java
2번째이후 사업장 등록 핀번호 받는 api 작성
포스트맨 완
> feat: 2번째이후 사업장 등록 핀번호 받는 api

- User/src/main/java/com/example/User/service/EmailService.java
> email url 프론트도메인 적용

- API-Gateway/src/main/java/com/example/API_Gateway/error/ErrorCode.java
- Attendance/src/main/java/com/example/Attendance/dto/CommuteByPresidentRequest.java
- Finance/src/main/java/com/example/Finance/controller/FinanceController.java
- User/src/main/java/com/example/User/dto/authserver/AuthServerEmailPinNumberRequest.java
- core-bank/src/main/java/com/example/core_bank/core_bank/core/dto/TransactionHistoryRequest.java
> deploy: 배포 test용 공백

- Attendance/src/main/java/com/example/Attendance/config/JobScheduler.java
> deploy: 테스트용 스케줄 1분

- Finance/Dockerfile
- Finance/src/main/java/com/example/Finance/service/PdfService.java
> fix : pdf 폰트 경로 변경

- Attendance/Dockerfile
- Attendance/src/main/java/com/example/Attendance/feign/FeignWithCoreBank.java
- Attendance/src/main/java/com/example/Attendance/service/batch/PdfService.java
> fix: pdf 서비스 수정 및 feign 수정

- Attendance/src/main/java/com/example/Attendance/config/JobScheduler.java
> fix: 자동이체 5분마다로 실행

- Attendance/build.gradle
- Attendance/src/main/java/com/example/Attendance/config/JobScheduler.java
> fix: config 의존성 제거

- User/src/main/java/com/example/User/controller/PresidentAccountController.java
- User/src/main/java/com/example/User/dto/login/ReqIdFindData.java
> merge : deploy <- dev 

- User/src/main/java/com/example/User/dto/store/StoreResponse.java
> fix: store_list 반환시 위도 경도 추가

- Attendance/src/test/java/com/example/Attendance/integration/AttendanceIntegrationTest.java
- Finance/build.gradle
- Finance/src/main/java/com/example/Finance/controller/FinanceController.java
- Finance/src/main/java/com/example/Finance/error/ErrorCode.java
- Finance/src/main/java/com/example/Finance/error/GlobalExceptionHandler.java
- Finance/src/main/java/com/example/Finance/service/IncomeStatementPdfService.java
- Finance/src/main/java/com/example/Finance/service/TransactionHistoryService.java
- Finance/src/main/java/com/example/Finance/service/UserInteractService.java
- Finance/src/test/java/com/example/Finance/integration/FinanceIntegrationTests.java
- User/src/main/java/com/example/User/controller/AuthController.java
- User/src/main/java/com/example/User/controller/PresidentAccountController.java
- User/src/main/java/com/example/User/controller/PresidentInfoController.java
- User/src/main/java/com/example/User/controller/StoreController.java
- User/src/main/java/com/example/User/dto/president/TermAcceptRequest.java
- User/src/main/java/com/example/User/dto/presidentupdate/PresidentUpdateRequest.java
- User/src/main/java/com/example/User/repository/StoreEmployeeRepository.java
- User/src/main/java/com/example/User/service/StoreEmployeeService.java
- User/src/test/java/com/example/User/integration/AccountAuthControllerTest.java
- User/src/test/java/com/example/User/integration/AuthControllerTest.java
- User/src/test/java/com/example/User/integration/CoreBankControllerTest.java
- User/src/test/java/com/example/User/integration/ManagerControllerTest.java
- User/src/test/java/com/example/User/integration/MockMvcTest.java
- User/src/test/java/com/example/User/integration/PresidentInfoControllerTest.java
- User/src/test/java/com/example/User/integration/StoreControllerTest.java
- User/src/test/java/com/example/User/integration/StoreEmployeeControllerTest.java
1. USER, FINANCE 부 통합 테스트 코드 작성
2. Finance 부 User 서비스 와 통신 간 예외 처리 추가
3. Finance 부 코어 뱅크와 통신 간 예외 처리 추가 
4. 생성자와 Setter 모두 없는 DTO 수정
TestCode로 진행했습니다.
> Fix : 통합 테스트 추가 및 기타 수정 

- User/src/main/java/com/example/User/service/EmailService.java
> fix: 출퇴근 url 프런트 도메인 변경

- Attendance/src/main/resources/application.yml
- Finance/src/main/resources/application.yml
- User/src/main/resources/application.yml
- core-bank/src/main/resources/application.yml
> fix: 시간대 변경

- Attendance/src/main/java/com/example/Attendance/config/TimezoneConfig.java
> fix: 시간대 변경 config

- Attendance/src/main/java/com/example/Attendance/service/CommuteService.java
> fix : LocalDateTime 한국 기준으로 변경

- Attendance/src/main/java/com/example/Attendance/service/CommuteService.java
- Attendance/src/main/resources/application.yml
> fix : LocalDateTime 한국 기준으로 변경(jdbc)

- Attendance/src/main/java/com/example/Attendance/service/CommuteService.java
> fix : commuteDate 날짜 변경 로직 수정

- Attendance/src/main/java/com/example/Attendance/model/Commute.java
- Attendance/src/main/java/com/example/Attendance/service/CommuteService.java
> fix : commuteDate 재 변경

- Attendance/src/main/resources/application.yml
> fix : commuteDate 재 변경(yaml)

- Attendance/src/main/java/com/example/Attendance/model/Commute.java
> fix : commuteDate 재 변경(직렬화)

- Attendance/src/main/java/com/example/Attendance/model/Commute.java
- Attendance/src/main/java/com/example/Attendance/service/CommuteService.java
fix : commuteDate 재 변경(toLocalDate 활용으로 인한 생성자 변경)
> fix : commuteDate 재 변경(toLocalDate 활용으로 인한 생성자 변경)

- Attendance/src/main/java/com/example/Attendance/dto/CommuteByPresidentRequest.java
fix : commuteDate 재 변경(DTO 오류 수정)
> fix : commuteDate 재 변경(DTO 오류 수정)

- Attendance/src/main/java/com/example/Attendance/controller/StoreEmployeeController.java
- Attendance/src/main/java/com/example/Attendance/model/Commute.java
- Attendance/src/main/java/com/example/Attendance/service/CommuteService.java
- Attendance/src/main/resources/application.yml
> Testdeploy

- Attendance/src/main/java/com/example/Attendance/service/CommuteService.java
> fix : log 추가

- Attendance/src/main/java/com/example/Attendance/controller/CommuteController.java
- Attendance/src/main/java/com/example/Attendance/repository/CommuteRepository.java
fix : update, 조회 부 시간대 변환 문제 해결
> fix : update, 조회 부 시간대 변환 문제 해결 

- Attendance/src/main/java/com/example/Attendance/AttendanceApplication.java
> fix : testing

- Attendance/src/main/java/com/example/Attendance/dto/CommuteByPresidentRequest.java
- Attendance/src/main/java/com/example/Attendance/service/CommuteService.java
> fix : zoneddatetime으로 dto 변경

- Attendance/src/main/resources/application.yml
fix : yaml 설정을 통해 time zone-> asia/seoul로 통일
> fix : yaml 설정을 통해 time zone-> asia/seoul로 통일

- Attendance/src/main/java/com/example/Attendance/controller/CommuteController.java
- Attendance/src/main/java/com/example/Attendance/model/Commute.java
fix : commuteDate DTO에서 받아오기로 변경.
> fix : commuteDate DTO에서 받아오기로 변경.

- Attendance/Dockerfile
- Attendance/src/main/java/com/example/Attendance/AttendanceApplication.java
- Attendance/src/main/resources/application.yml
fix : YAML, DOCKERFILE, JVM LEVEL TIMEZONE 변경
> fix : YAML, DOCKERFILE, JVM LEVEL TIMEZONE 변경

- Attendance/src/main/java/com/example/Attendance/model/Commute.java
fix : CommuteDate 계산 로직 제거 및 입력 값 그대로 활용 로직으로 롤백
#테스트
배포 환경에서 Test 완료하였습니다. 
로직 간편화를 위해 해당 부만 추가 수정하였습니다.
> fix : CommuteDate 계산 로직 제거,
